language: node_js
# Leave node_js version blank to
# use version in `.nvmrc`
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm install -g @angular/cli codecov
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - codecov
